/**:
  ros__parameters:
    speed_to_erpm_gain: 4615.0
    speed_to_erpm_offset: 0.0
    steering_angle_to_servo_gain: -0.9135
    steering_angle_to_servo_offset: 0.48
    wheelbase: 0.3175
    max_erpm_positive_delta: 500.0  # limits the sudden acceleration in rpm
    max_erpm_negative_delta: 1000.0 # limits the sudden deceleration in rpm